### ISSUE TITLE
Pagination UI did not get update after reset search

### ISSUE THREAD

**Issue by rahulguptafullstack** [rmartide/react-reacstrap-pagination#12]
Hi,
I have issue of UI of pagination not getting reset page 1 after reset the search result.
For ex. I am on page number 4 then I click to the reset button and set selected Page to 1 in state.
State is setting up properly but still I am seeing page number is active instead of page number 1.

![page_number_issue](https://user-images.githubusercontent.com/42096575/65016076-df5c1900-d940-11e9-9620-8344e2515cf0.png)

Thanks

**Comment by ddarren** [comment]
I was running into a similar problem and I just set the `activePage` prop.
```
<PaginationComponent activePage={this.state.page}... />
```
The `this.state.page` comes from my own component which gets set by the `onSelect` of `PaginationComponent`. And I set a default state of 1 in the consturctor:

```
  constructor(props) {
    super(props);
    this.state = { page: 1 };
  }
```

**Comment by rmartide** [comment]
It has been a while but I have updated the component and now it correctly updates itself everytime a prop is changed.
