### ISSUE TITLE
Is it possible to precise a size of the component

### ISSUE THREAD

**Issue by dominique-bureau** [rmartide/react-reacstrap-pagination#13]
Hi Rodrigo
First, thanks for your component for the pagination. Sure it will help me. 

I have a question about this component. According the documentation (https://reactstrap.github.io/components/pagination/), the props "size" exists : 

<Pagination size="sm" aria-label="Page navigation example">

But If I call the component with this props "size" like that 

<PaginationComponent
                                **size="sm"**
                                totalItems={meta.total}
                                pageSize={meta.per_page}
                                onSelect={this.handleSelectedPage}
                                // maxPaginationNumbers={10}
                                activePage={selectedPage}
                                firstPageText="|<"
                                previousPageText="<<"
                                nextPageText=">>"
                                lastPageText=">|"      
                            />

it seems it does not work. But certainly you did not add that.

My question is : how can I do to add this value "sm" each time I call the component ? Simple , ou complicated to do ? (I am a very beginner in react)

Thanks again Rodrigo for this work. 

Dom

**Comment by rmartide** [comment]
Hi Dominique,

Since it was a very easy feature I added it, now you just need to add the prop size with the values "sm" or "lg".

Thanks for the idea.

Cheers
