### ISSUE TITLE
Getting a warning of use of Deprecated React lifecycle method

### ISSUE THREAD

**Issue by scryan7371** [rmartide/react-reacstrap-pagination#14]
backend.js:6 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: PaginationComponent

**Comment by rmartide** [comment]
You are right, I knew I had to change it someday, it was a pull request and even though I didn't like it that much I let it pass for a while.

I'm using a pure component to remove it but since this will make other changes in props to trigger a render I am going to need a bit more time.

After fixing this issue I will take a look at the other issue, number 15. Hopefully both will be fixed this weekend.

**Comment by scryan7371** [comment]
No problem this is a super useful plugin.  It is unfortunate the react framework undergoes such radical changes even though it is old now.  I have not seen such drastic re-architecture in other frameworks I use and it makes it hard to get corporations to commit to it.  No hurry.  I tried to address it myself going to a functional component but the craziness of that change is too much for me to undertake with other things on my plate.  Thanks again for a great plugin

**Comment by rmartide** [comment]
Thanks man, you are right. Now with hooks it's even another level although I think it is for the best.

I'm closing this issue since I just published the change.
