### ISSUE TITLE
Create types file for this component

### ISSUE THREAD

**Issue by scryan7371** [rmartide/react-reacstrap-pagination#15]
I use react with typescript and this project does not produce a types file so that typescript compiler complains.  Is there any way to produce one as part of this project.

**Comment by rmartide** [comment]
I created the type file, although in some functions I let type any since I was not sure what type I should use.

I added the file to the package.json's types property, to be honest I don't know if I missed any step.

Let me know if the compiler keeps complaining and I will create a typescript project to test it, thinking now about it I should've done that before publishing it...

**Comment by scryan7371** [comment]
Thanks I will try it out as well

**Comment by scryan7371** [comment]
Whatever you did broke the component.  There is not type for the onSelect and somehow it is throwing all sorts of errors and not working.  I am not able to use the 2.0.X any longer in a type script project.  I also don't see any @types file so it must be embedded.  I will roll back the version and send you a test project in a week to test the typescript with

**Comment by rmartide** [comment]
I've done what I should've done before publishing it and created a typescript project.

You were right, it didn't like the missing type. I added the type and it works fine now in 2.0.2.

Try it and tell me, it should work fine but I will leave the issue open until then.

**Comment by scryan7371** [comment]
Very close. Can you use number rather than Number as that is a typescript violation?  It is working with Number now but getting typescript warnings for using Number rather than number.  Getting on a flight so will try soon.

**Comment by rmartide** [comment]
Oh jeez, I'm dumb, I was using number on all the other types and for some reason I used Number there...

**Comment by scryan7371** [comment]
No worries it is a great component I am on flight but will try it when we land   Getting close lol. Thanks for all the hard work
