### ISSUE TITLE
Start from 1

### ISSUE THREAD

**Issue by ahmeed83** [rmartide/react-reacstrap-pagination#16]
The list that I'm getting from the backend start with 0. But the one that this components start with is 1. Can it start fro 0 as well?

**Comment by rmartide** [comment]
I really don't get the issue here, can't you substract one on the handle click method?

**Comment by ahmeed83** [comment]
You don't provide a variable where you can specify the page number. So I can't subtract it. 

My page number starts with 0 and this component starts at 1.

**Comment by rmartide** [comment]
There's a prop for that called onSelect. 

It returns the number of the selected page.

You have here an example of use: [example](https://codesandbox.io/s/2z5jw7mnkp).

Method handleSelected.

**Comment by ahmeed83** [comment]
This method will kick off when you click on the buttons. 

My problem is when you go to the next page (or the last page) you can't go back to the very first page again. It always sends you back to page number one and not page number zero. There is no way to go to page number zero only when you refresh the page

**Comment by rmartide** [comment]
That is not true, as you can see on the example. 

You have a First button. Clicking on that button you can go back to the very first page.

**Comment by rmartide** [comment]
You keep saying page number zero but there is not page number zero.

If your backend starts on page number 0 just imagine that is the page 1 so you have 2 options, the worst is adding 1 to all pages one you get them from the backend or just to substract 1 on the handle selected method.

**Comment by ahmeed83** [comment]
Yes you are right. Now I see it. 

`  const handleSelected = index => {
    props.setPageNumber(index - 1);
  };
`
This fixed the problem.

Thanks for the support!
