### ISSUE TITLE
 multiple pagination?

### ISSUE THREAD

**Issue by morewater** [rmartide/react-reacstrap-pagination#18]
Hey 

How to sync the pagination  ?

I got two pagination at table top and buttom .
but no prop like current page ,that I can't sync the state via current page ...

**Comment by rmartide** [comment]
Hi, you can sync using defaultActivePage.

So you could sync two by having the defaultActivePage on the state and then updating the state with the value that you get back on the onSelect method.

**Comment by rmartide** [comment]
I made a quick example

https://codesandbox.io/s/magical-shtern-1hjyh
