### ISSUE TITLE
activePage prop

### ISSUE THREAD

**Issue by JalalAlbasri** [rmartide/react-reacstrap-pagination#2]
Hi, 
Would it be possible to have an activePage prop we can pass in. 
It would be useful if for example I wanted to go directly to xyz.com/new?page=2

I'll give implementing it a shot this weekend.

Thank You.

**Comment by JalalAlbasri** [comment]
Hi, It was easier than I thought, Implemented it here. 

https://github.com/JalalAlbasri/react-reacstrap-pagination

**Comment by rmartide** [comment]
Hi,
Thanks for the implementation and the bug fix.

It is merged now.
