### ISSUE TITLE
Page numbers are not coming correctly

### ISSUE THREAD

**Issue by shubhamnagota** [rmartide/react-reacstrap-pagination#4]
Hi, 
I have created a PaginationComponent and I am getting wrong count.

Example:
 <PaginationComponent
        totalItems={444}
        pageSize={10}
        onSelect={this.handleClick.bind(this)}
        maxPaginationNumbers={5}
   />

The actual page count should be 44 but it is 45.

**Comment by rmartide** [comment]
Hi,
Can you tell me the total number of elements and the page size?

I have been trying to replicate it but the component seems to work fine.

**Comment by shubhamnagota** [comment]
Hi, There was some issue with data while changing data from slicing the array and showing it.
Please add an example by fetching the data and showing it. That will help a lot.

You can close the issue. Thanks.
